version: "3.6"

services:
  # mongo service
  kickups-mongodb-local:
    image: mongo:latest
    container_name: kickups-mongodb-local
    command: mongod --port 27057
    ports:
      - 27057:27057
    expose:
      - 27057
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo_net

volumes:
  mongo-data:

networks:
  mongo_net:
    driver: bridge
